import type { Metadata } from "next";
import { Gideon_Roman, Arimo, Nunito_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Header from "@/components/Header";

const mainFont = Gideon_Roman({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-main",
});
const subFont = Nunito_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "700"],
  variable: "--font-sub",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${mainFont.className} ${mainFont.variable} ${subFont.variable} flex flex-col h-screen text-primary-color bg-black px-32 py-4`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
